# Generated by Django 2.0.7 on 2018-08-04 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='category',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together={('id', 'slug')},
        ),
    ]
