# Generated by Django 2.0.7 on 2018-08-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0002_auto_20180804_0521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allergen',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='store',
            name='slug',
        ),
        migrations.AlterField(
            model_name='allergen',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AlterIndexTogether(
            name='category',
            index_together=set(),
        ),
        migrations.AlterIndexTogether(
            name='product',
            index_together=set(),
        ),
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
