# Generated by Django 2.0.7 on 2018-08-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0004_auto_20180804_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.CharField(db_index=True, default='random', max_length=250),
        ),
    ]
