# Generated by Django 2.0.7 on 2018-08-04 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0005_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='allergens',
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(db_index=True, default=None, max_length=250),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.CharField(db_index=True, default=None, max_length=250),
        ),
    ]
