# Generated by Django 2.0.7 on 2018-08-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0006_auto_20180805_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='username',
            field=models.CharField(max_length=250),
        ),
    ]
