# Generated by Django 2.0.7 on 2018-08-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0006_auto_20180805_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='product',
            name='stores',
        ),
        migrations.AddField(
            model_name='product',
            name='stores',
            field=models.CharField(db_index=True, default=None, max_length=250),
        ),
    ]
