# Generated by Django 2.0.7 on 2018-08-04 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('allergyshop', '0007_auto_20180805_0231'),
        ('allergyshop', '0007_auto_20180805_0023'),
    ]

    operations = [
    ]
